//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace applyRequests.Tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class alluser
    {
        public short seq { get; set; }
        public string name { get; set; }
        public string regin { get; set; }
        public string regout { get; set; }
        public string regs { get; set; }
        public string addr { get; set; }
        public string uid { get; set; }
        public string uoid { get; set; }
        public string upwd { get; set; }
        public string usrgrp { get; set; }
        public string userright { get; set; }
        public string sarea { get; set; }
        public string specialo { get; set; }
        public string specialx { get; set; }
        public bool show { get; set; }
        public bool staff { get; set; }
        public string ordertype { get; set; }
        public string bdy { get; set; }
        public string bdmn { get; set; }
        public int skey { get; set; }
    }
}
